### ISSUE TITLE
Push Cashrawer

### ISSUE THREAD

**Issue by sidikbilardi** [adenvt/recta#2]
is recta can push cashdrawer on Client POS Thermal Printer?

**Comment by adenvt** [comment]
there isn't build-in function for cashdrawer yet, but you can send raw **ESC/POS** command to push cashdrawer using `.raw()` function.

example for Generic EPSON Printer
```js
recta.raw([0x1b, 0x70, 0x00]) // Sends a pulse to pin 2 []

// or 

recta.raw([0x1b, 0x70, 0x01]) // Sends a pulse to pin 5 []
```
